### ISSUE TITLE
Love this repo, how to use?

### ISSUE THREAD

**Issue by jfmatth** [openshift-evangelists/openshift-cookbook#7]
Hi Graham, 

I love this REPO, thank you!

I'm not familiar this how this repo is used.  I see a readme, summary and intro (.md) and i think it's based on gitbook,io, but not sure if there is a way to see a 'published' version.

thanks,

J

**Comment by GrahamDumpleton** [comment]
For now it is published at;

* http://cookbook.openshift.org

It is likely to be moved elsewhere at some point, but for now you can see it there.
